'use client'

import { TableBody, TableCell, TableHeader, TableRow, Table, TableHead } from "@/components/ui/table"
import { useSearchParams } from "next/navigation"
import { getPluginData } from "@/actions/plugin-data"
import { use, useState, useMemo } from "react"
import { getPluginInsights } from "@/actions/suggerence"
import { decode } from "html-entities"
import Link from "next/link"
import { useEffect } from "react"
import { Loader2 } from "lucide-react"
import { Button } from "../ui/button"
import { formatRelativeTime, formatActiveInstallations } from '@/lib/utils'

export const CompareResults = () => {

    const urlParams = useSearchParams()
    const plugins = useMemo(() => urlParams.get('plugins')?.split(',') || [], [urlParams])

    const [pluginsData, setPluginsData] = useState<WordPressPlugin[]>([])
    const [pluginsInsights, setPluginsInsights] = useState<SuggerencePluginInsights[]>([])

    useEffect(() => {
        if (plugins.length === 0) return
        
        const fetchPluginsData = async () => {
            const pluginsData = await getPluginData(plugins)
            const pluginsInsights = await Promise.all(plugins.map((plugin) => getPluginInsights(plugin)))
            setPluginsData(pluginsData)
            setPluginsInsights(pluginsInsights)
        }
        fetchPluginsData()
    }, [plugins])

    // Helper function to render cell content based on row key
    const renderCellContent = (rowKey: string, value: any, source: 'insights' | 'data') => {
        if (!value && value !== 0) return '';

        switch (rowKey) {
            case 'category':
                return <span className="capitalize">{value}</span>
            case 'complexity_level':
                return <span className="capitalize">{value}</span>
            case 'rating':
                if (source === 'data' && typeof value === 'number') {
                    // Rating might be out of 100, so normalize to 0-5 scale
                    const normalizedRating = value > 5 ? value / 20 : value;
                    const rating = Math.max(0, Math.min(5, Math.round(normalizedRating)));
                    const stars = '★'.repeat(rating) + '☆'.repeat(5 - rating);
                    return `${stars} (${normalizedRating.toFixed(1)}/5)`;
                }
                return decode(String(value));

            case 'last_updated':
                return formatRelativeTime(String(value))
            case 'added':
                if (source === 'data' && value) {
                    try {
                        const date = new Date(value);
                        return date.toLocaleDateString('en-US', {
                            year: 'numeric',
                            month: 'short',
                            day: 'numeric'
                        });
                    } catch {
                        return decode(String(value));
                    }
                }
                return decode(String(value));

            case 'active_installs':
                return formatActiveInstallations(value);

            case 'num_ratings':
                if (source === 'data' && typeof value === 'number') {
                    return value.toLocaleString();
                }
                return decode(String(value));

            case 'features':
            case 'tags':
                if (source === 'insights' && Array.isArray(value)) {
                    return value.join(', ');
                }
                return Array.isArray(value) ? value.join(', ') : decode(String(value));

            case 'requires_plugins':
                if (source === 'data' && Array.isArray(value)) {
                    return value.length > 0 ? value.join(', ') : 'None';
                }
                return Array.isArray(value) ? value.join(', ') : decode(String(value));

            default:
                if (Array.isArray(value)) {
                    return value.join(', ');
                }
                return decode(String(value));
        }
    };

    if (!pluginsData.length || !pluginsInsights.length) {
        return (
            <div className="p-6">
                <div className="flex items-center justify-center h-full">
                    <Loader2 className="w-6 h-6 animate-spin" />
                </div>
            </div>
        )
    }

    const rows: Array<{
        title: string;
        subtitle?: string;
        key: string;
        source: 'insights' | 'data';
    }> = [
        {
            title: 'Main Purpose',
            subtitle: 'Generated by AI',
            key: 'main_purpose',
            source: 'insights',
        },
        {
            title: 'Summary',
            subtitle: 'Generated by AI',
            key: 'summary',
            source: 'insights',
        },
        {
            title: 'Category',
            subtitle: 'Generated by AI',
            key: 'category',
            source: 'insights',
        },
        {
            title: 'Complexity Level',
            subtitle: 'Generated by AI',
            key: 'complexity_level',
            source: 'insights',
        },
        {
            title: 'Features',
            subtitle: 'Generated by AI',
            key: 'features',
            source: 'insights',
        },
        {
            title: 'Tags',
            subtitle: 'Generated by AI',
            key: 'tags',
            source: 'insights',
        },
        {
            title: 'Requires',
            key: 'requires',
            source: 'data',
        },
        {
            title: 'Tested',
            key: 'tested',
            source: 'data',
        },
        {
            title: 'Requires PHP',
            key: 'requires_php',
            source: 'data',
        },
        {
            title: 'Requires Plugins',
            key: 'requires_plugins',
            source: 'data',
        },
        {
            title: 'Rating',
            key: 'rating',
            source: 'data',
        },
        {
            title: 'Number of Ratings',
            key: 'num_ratings',
            source: 'data',
        },
        {
            title: 'Active Installations',
            key: 'active_installs',
            source: 'data',
        },
        {
            title: 'Last Updated',
            key: 'last_updated',
            source: 'data',
        },
        {
            title: 'Added',
            key: 'added',
            source: 'data',
        }
    ]

    return (
        <div className="p-6">
            <Table className="table-fixed">
                <TableHeader>
                    <TableRow>
                        <TableHead className="w-1/5"></TableHead>
                        {plugins.map((plugin, index) => (
                            <TableHead key={plugin} className="w-1/5 align-top p-4 whitespace-normal">
                                <Link href={`/${plugin}`} target="_blank">
                                    <div className="flex items-start gap-2">
                                        {pluginsData[index]?.icons && (
                                            <img 
                                                className="w-[50px] h-[50px] flex-shrink-0" 
                                                src={Object.values(pluginsData[index].icons).pop() as string} 
                                                alt={pluginsData[index].name} 
                                            />
                                        )}
                                        <p className="text-[14px] font-[400] text-[#656a71] line-clamp-2 break-words overflow-wrap-anywhere">
                                            {pluginsData[index] ? decode(pluginsData[index].name) : plugin}
                                        </p>
                                    </div>
                                </Link>
                            </TableHead>
                        ))}
                    </TableRow>
                </TableHeader>
                <TableBody>
                    {rows.map((row, index) => (
                        <TableRow key={index}>
                            <TableCell>
                                <h2>{row.title}</h2>
                                {row.subtitle && (
                                    <p className="text-[12px] font-[400] text-muted-foreground">{row.subtitle}</p>
                                )}
                            </TableCell>

                            {plugins.map((plugin, index) => {
                                const value = row.source === 'insights' 
                                    ? pluginsInsights[index]?.[row.key as keyof SuggerencePluginInsights]
                                    : pluginsData[index]?.[row.key as keyof WordPressPlugin];
                                
                                return (
                                    <TableCell key={plugin} className="align-top p-4 max-w-0 whitespace-normal text-sm">
                                        <div className="break-words overflow-wrap-anywhere text-xs leading-relaxed">
                                            {renderCellContent(row.key, value, row.source)}
                                        </div>
                                    </TableCell>
                                );
                            })}
                        </TableRow>
                    ))}

                    <TableRow>
                        <TableCell></TableCell>
                        {plugins.map((plugin, index) => (
                            <TableCell key={plugin} className="align-top p-4 max-w-0 whitespace-normal text-sm">
                                <div className="flex flex-col gap-2">
                                    <Link href={pluginsData[index].download_link} target="_blank">
                                        <Button className="w-full" variant="wordpress">Download</Button>
                                    </Link>

                                    {pluginsData[index].preview_link && (
                                        <Link href={pluginsData[index].preview_link} target="_blank">
                                            <Button className="w-full" variant="outline">Live Preview</Button>
                                        </Link>
                                    )}
                                </div>
                            </TableCell>
                        ))}
                    </TableRow>
                </TableBody>
            </Table>
        </div>
    )
}